import { db } from '@/db';
import { activityLogs } from '@/db/schema';

async function main() {
    const sampleActivityLogs = [
        // Complaint submissions (50 entries)
        {
            userId: 1,
            complaintId: 1,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'high', location: 'Dadar, Mumbai' },
            createdAt: new Date('2024-01-15T09:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 2,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'critical', location: 'Bandra, Mumbai' },
            createdAt: new Date('2024-01-15T10:30:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 3,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'medium', location: 'Andheri, Mumbai' },
            createdAt: new Date('2024-01-16T08:15:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 4,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'low', location: 'Kurla, Mumbai' },
            createdAt: new Date('2024-01-16T14:20:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 5,
            action: 'complaint_submitted',
            details: { category: 'water', priority: 'high', location: 'Malad, Mumbai' },
            createdAt: new Date('2024-01-17T07:45:00Z').toISOString(),
        },

        // Status updates (20 entries)
        {
            userId: 11,
            complaintId: 1,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Infrastructure Manager' },
            createdAt: new Date('2024-01-15T11:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 2,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Sanitation Manager' },
            createdAt: new Date('2024-01-15T12:00:00Z').toISOString(),
        },
        {
            userId: 13,
            complaintId: 3,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Transport Manager' },
            createdAt: new Date('2024-01-16T10:00:00Z').toISOString(),
        },
        {
            userId: 14,
            complaintId: 4,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Streetlight Manager' },
            createdAt: new Date('2024-01-16T16:00:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 5,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Water Manager' },
            createdAt: new Date('2024-01-17T09:30:00Z').toISOString(),
        },

        // Assignments (15 entries)
        {
            userId: 11,
            complaintId: 1,
            action: 'assigned',
            details: { assignedTo: 'Infrastructure Manager', department: 'infrastructure' },
            createdAt: new Date('2024-01-15T11:05:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 2,
            action: 'assigned',
            details: { assignedTo: 'Sanitation Manager', department: 'sanitation' },
            createdAt: new Date('2024-01-15T11:30:00Z').toISOString(),
        },
        {
            userId: 13,
            complaintId: 3,
            action: 'assigned',
            details: { assignedTo: 'Transport Manager', department: 'transport' },
            createdAt: new Date('2024-01-16T10:15:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 5,
            action: 'assigned',
            details: { assignedTo: 'Water Manager', department: 'water' },
            createdAt: new Date('2024-01-17T09:45:00Z').toISOString(),
        },
        {
            userId: 16,
            complaintId: 6,
            action: 'assigned',
            details: { assignedTo: 'Health Manager', department: 'health' },
            createdAt: new Date('2024-01-17T11:00:00Z').toISOString(),
        },

        // Resolved complaints (10 entries)
        {
            userId: 11,
            complaintId: 1,
            action: 'resolved',
            details: { resolvedBy: 'Infrastructure Manager', resolutionTime: '5 days' },
            createdAt: new Date('2024-01-20T14:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 2,
            action: 'resolved',
            details: { resolvedBy: 'Sanitation Manager', resolutionTime: '3 days' },
            createdAt: new Date('2024-01-18T16:00:00Z').toISOString(),
        },
        {
            userId: 13,
            complaintId: 3,
            action: 'resolved',
            details: { resolvedBy: 'Transport Manager', resolutionTime: '7 days' },
            createdAt: new Date('2024-01-23T10:00:00Z').toISOString(),
        },
        {
            userId: 14,
            complaintId: 4,
            action: 'resolved',
            details: { resolvedBy: 'Streetlight Manager', resolutionTime: '2 days' },
            createdAt: new Date('2024-01-18T18:00:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 5,
            action: 'resolved',
            details: { resolvedBy: 'Water Manager', resolutionTime: '4 days' },
            createdAt: new Date('2024-01-21T12:00:00Z').toISOString(),
        },

        // Feedback given (30 entries)
        {
            userId: 1,
            complaintId: 1,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Excellent work! The road was fixed perfectly.' },
            createdAt: new Date('2024-01-20T15:30:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 2,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Good service, but took a bit long.' },
            createdAt: new Date('2024-01-18T17:00:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 3,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Very satisfied with the resolution.' },
            createdAt: new Date('2024-01-23T11:00:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 4,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Quick response and fixed immediately.' },
            createdAt: new Date('2024-01-18T19:00:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 5,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Water supply restored. Thank you!' },
            createdAt: new Date('2024-01-21T13:30:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 6,
            action: 'complaint_submitted',
            details: { category: 'health', priority: 'high', location: 'Borivali, Mumbai' },
            createdAt: new Date('2024-01-17T10:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 7,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'critical', location: 'Powai, Mumbai' },
            createdAt: new Date('2024-01-18T09:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 8,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Ghatkopar, Mumbai' },
            createdAt: new Date('2024-01-18T11:30:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 9,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Thane, Mumbai' },
            createdAt: new Date('2024-01-19T08:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 10,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'medium', location: 'Vashi, Mumbai' },
            createdAt: new Date('2024-01-19T10:45:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 7,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Infrastructure Manager' },
            createdAt: new Date('2024-01-18T11:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 8,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Sanitation Manager' },
            createdAt: new Date('2024-01-18T13:00:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 7,
            action: 'assigned',
            details: { assignedTo: 'Infrastructure Manager', department: 'infrastructure' },
            createdAt: new Date('2024-01-18T11:15:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 8,
            action: 'assigned',
            details: { assignedTo: 'Sanitation Manager', department: 'sanitation' },
            createdAt: new Date('2024-01-18T13:15:00Z').toISOString(),
        },
        {
            userId: 16,
            complaintId: 6,
            action: 'resolved',
            details: { resolvedBy: 'Health Manager', resolutionTime: '6 days' },
            createdAt: new Date('2024-01-23T15:00:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 7,
            action: 'resolved',
            details: { resolvedBy: 'Infrastructure Manager', resolutionTime: '8 days' },
            createdAt: new Date('2024-01-26T10:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 8,
            action: 'resolved',
            details: { resolvedBy: 'Sanitation Manager', resolutionTime: '5 days' },
            createdAt: new Date('2024-01-23T14:00:00Z').toISOString(),
        },
        {
            userId: 13,
            complaintId: 9,
            action: 'resolved',
            details: { resolvedBy: 'Transport Manager', resolutionTime: '4 days' },
            createdAt: new Date('2024-01-23T11:00:00Z').toISOString(),
        },
        {
            userId: 14,
            complaintId: 10,
            action: 'resolved',
            details: { resolvedBy: 'Streetlight Manager', resolutionTime: '3 days' },
            createdAt: new Date('2024-01-22T16:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 6,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Great response to health concern!' },
            createdAt: new Date('2024-01-23T16:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 7,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Good work, though it took some time.' },
            createdAt: new Date('2024-01-26T11:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 8,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Very satisfied with the cleanliness now.' },
            createdAt: new Date('2024-01-23T15:00:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 9,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Bus stop is now clean and well-maintained.' },
            createdAt: new Date('2024-01-23T12:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 10,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Streetlight fixed promptly. Thank you!' },
            createdAt: new Date('2024-01-22T17:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 11,
            action: 'complaint_submitted',
            details: { category: 'water', priority: 'high', location: 'Kandivali, Mumbai' },
            createdAt: new Date('2024-01-20T09:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 12,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'critical', location: 'Mulund, Mumbai' },
            createdAt: new Date('2024-01-20T11:30:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 13,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Chembur, Mumbai' },
            createdAt: new Date('2024-01-21T08:15:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 14,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Goregaon, Mumbai' },
            createdAt: new Date('2024-01-21T10:45:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 15,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'medium', location: 'Versova, Mumbai' },
            createdAt: new Date('2024-01-22T07:30:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 11,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Water Manager' },
            createdAt: new Date('2024-01-20T11:00:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 12,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Infrastructure Manager' },
            createdAt: new Date('2024-01-20T13:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 13,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Sanitation Manager' },
            createdAt: new Date('2024-01-21T10:00:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 11,
            action: 'assigned',
            details: { assignedTo: 'Water Manager', department: 'water' },
            createdAt: new Date('2024-01-20T11:15:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 12,
            action: 'assigned',
            details: { assignedTo: 'Infrastructure Manager', department: 'infrastructure' },
            createdAt: new Date('2024-01-20T13:15:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 16,
            action: 'complaint_submitted',
            details: { category: 'health', priority: 'high', location: 'Jogeshwari, Mumbai' },
            createdAt: new Date('2024-01-22T09:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 17,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'medium', location: 'Vikhroli, Mumbai' },
            createdAt: new Date('2024-01-22T11:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 18,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'critical', location: 'Khar, Mumbai' },
            createdAt: new Date('2024-01-23T08:30:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 19,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'high', location: 'Santacruz, Mumbai' },
            createdAt: new Date('2024-01-23T10:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 20,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'low', location: 'Mahim, Mumbai' },
            createdAt: new Date('2024-01-23T12:15:00Z').toISOString(),
        },
        {
            userId: 16,
            complaintId: 16,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Health Manager' },
            createdAt: new Date('2024-01-22T11:00:00Z').toISOString(),
        },
        {
            userId: 12,
            complaintId: 18,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Sanitation Manager' },
            createdAt: new Date('2024-01-23T10:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 21,
            action: 'complaint_submitted',
            details: { category: 'water', priority: 'critical', location: 'Matunga, Mumbai' },
            createdAt: new Date('2024-01-24T08:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 22,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'high', location: 'Wadala, Mumbai' },
            createdAt: new Date('2024-01-24T10:30:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 23,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Sion, Mumbai' },
            createdAt: new Date('2024-01-24T12:00:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 24,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Lower Parel, Mumbai' },
            createdAt: new Date('2024-01-25T09:15:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 25,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'high', location: 'Prabhadevi, Mumbai' },
            createdAt: new Date('2024-01-25T11:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 11,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Water supply issues resolved satisfactorily.' },
            createdAt: new Date('2024-01-25T14:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 12,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Excellent infrastructure repair work!' },
            createdAt: new Date('2024-01-26T12:00:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 13,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Good sanitation service provided.' },
            createdAt: new Date('2024-01-25T16:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 26,
            action: 'complaint_submitted',
            details: { category: 'health', priority: 'medium', location: 'Worli, Mumbai' },
            createdAt: new Date('2024-01-25T13:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 27,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'critical', location: 'Tardeo, Mumbai' },
            createdAt: new Date('2024-01-26T08:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 28,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'high', location: 'Byculla, Mumbai' },
            createdAt: new Date('2024-01-26T10:30:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 29,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'medium', location: 'Parel, Mumbai' },
            createdAt: new Date('2024-01-26T12:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 30,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'low', location: 'Elphinstone Road, Mumbai' },
            createdAt: new Date('2024-01-27T09:00:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 21,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'assigned', updatedBy: 'Water Manager' },
            createdAt: new Date('2024-01-24T10:00:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 22,
            action: 'status_updated',
            details: { oldStatus: 'submitted', newStatus: 'in_progress', updatedBy: 'Infrastructure Manager' },
            createdAt: new Date('2024-01-24T12:00:00Z').toISOString(),
        },
        {
            userId: 15,
            complaintId: 21,
            action: 'assigned',
            details: { assignedTo: 'Water Manager', department: 'water' },
            createdAt: new Date('2024-01-24T10:15:00Z').toISOString(),
        },
        {
            userId: 11,
            complaintId: 22,
            action: 'assigned',
            details: { assignedTo: 'Infrastructure Manager', department: 'infrastructure' },
            createdAt: new Date('2024-01-24T12:15:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 14,
            action: 'feedback_given',
            details: { rating: 3, comment: 'Transport issue partially resolved.' },
            createdAt: new Date('2024-01-26T15:00:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 15,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Streetlights working perfectly now!' },
            createdAt: new Date('2024-01-26T17:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 16,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Health inspection conducted well.' },
            createdAt: new Date('2024-01-27T10:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 17,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Infrastructure problem solved efficiently.' },
            createdAt: new Date('2024-01-27T12:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 18,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Sanitation improved significantly.' },
            createdAt: new Date('2024-01-27T14:00:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 19,
            action: 'feedback_given',
            details: { rating: 3, comment: 'Transport service could be better.' },
            createdAt: new Date('2024-01-27T16:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 20,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Streetlight issue resolved promptly.' },
            createdAt: new Date('2024-01-28T09:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 31,
            action: 'complaint_submitted',
            details: { category: 'water', priority: 'high', location: 'Charni Road, Mumbai' },
            createdAt: new Date('2024-01-27T11:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 32,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'critical', location: 'Grant Road, Mumbai' },
            createdAt: new Date('2024-01-28T08:00:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 33,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Marine Lines, Mumbai' },
            createdAt: new Date('2024-01-28T10:30:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 34,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Churchgate, Mumbai' },
            createdAt: new Date('2024-01-28T12:00:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 35,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'high', location: 'Nariman Point, Mumbai' },
            createdAt: new Date('2024-01-29T09:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 21,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Water supply fully restored. Great job!' },
            createdAt: new Date('2024-01-28T14:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 22,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Infrastructure work completed well.' },
            createdAt: new Date('2024-01-28T16:00:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 23,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Sanitation standards improved greatly.' },
            createdAt: new Date('2024-01-29T10:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 36,
            action: 'complaint_submitted',
            details: { category: 'health', priority: 'critical', location: 'Colaba, Mumbai' },
            createdAt: new Date('2024-01-29T11:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 37,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'high', location: 'Fort, Mumbai' },
            createdAt: new Date('2024-01-29T13:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 38,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Bhandup, Mumbai' },
            createdAt: new Date('2024-01-30T08:00:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 39,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Kanjurmarg, Mumbai' },
            createdAt: new Date('2024-01-30T10:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 40,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'medium', location: 'Nahur, Mumbai' },
            createdAt: new Date('2024-01-30T12:00:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 24,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Transport connectivity improved.' },
            createdAt: new Date('2024-01-30T14:00:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 25,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Streetlight maintenance excellent!' },
            createdAt: new Date('2024-01-30T16:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 26,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Health services responded well.' },
            createdAt: new Date('2024-01-31T09:00:00Z').toISOString(),
        },
        {
            userId: 1,
            complaintId: 41,
            action: 'complaint_submitted',
            details: { category: 'water', priority: 'high', location: 'Ulhasnagar, Mumbai' },
            createdAt: new Date('2024-01-30T14:00:00Z').toISOString(),
        },
        {
            userId: 2,
            complaintId: 42,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'critical', location: 'Dombivli, Mumbai' },
            createdAt: new Date('2024-01-31T08:00:00Z').toISOString(),
        },
        {
            userId: 3,
            complaintId: 43,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'medium', location: 'Kalyan, Mumbai' },
            createdAt: new Date('2024-01-31T10:00:00Z').toISOString(),
        },
        {
            userId: 4,
            complaintId: 44,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'low', location: 'Badlapur, Mumbai' },
            createdAt: new Date('2024-01-31T12:00:00Z').toISOString(),
        },
        {
            userId: 5,
            complaintId: 45,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'high', location: 'Ambernath, Mumbai' },
            createdAt: new Date('2024-02-01T09:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 27,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Infrastructure repair exceptional!' },
            createdAt: new Date('2024-01-31T14:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 28,
            action: 'feedback_given',
            details: { rating: 4, comment: 'Sanitation problem addressed properly.' },
            createdAt: new Date('2024-01-31T16:00:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 29,
            action: 'feedback_given',
            details: { rating: 3, comment: 'Transport issue needs more attention.' },
            createdAt: new Date('2024-02-01T10:00:00Z').toISOString(),
        },
        {
            userId: 6,
            complaintId: 46,
            action: 'complaint_submitted',
            details: { category: 'health', priority: 'medium', location: 'Titwala, Mumbai' },
            createdAt: new Date('2024-02-01T11:00:00Z').toISOString(),
        },
        {
            userId: 7,
            complaintId: 47,
            action: 'complaint_submitted',
            details: { category: 'infrastructure', priority: 'high', location: 'Vasai, Mumbai' },
            createdAt: new Date('2024-02-01T13:00:00Z').toISOString(),
        },
        {
            userId: 8,
            complaintId: 48,
            action: 'complaint_submitted',
            details: { category: 'sanitation', priority: 'critical', location: 'Virar, Mumbai' },
            createdAt: new Date('2024-02-02T08:00:00Z').toISOString(),
        },
        {
            userId: 9,
            complaintId: 49,
            action: 'complaint_submitted',
            details: { category: 'transport', priority: 'medium', location: 'Nalasopara, Mumbai' },
            createdAt: new Date('2024-02-02T10:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 50,
            action: 'complaint_submitted',
            details: { category: 'streetlight', priority: 'low', location: 'Mira Road, Mumbai' },
            createdAt: new Date('2024-02-02T12:00:00Z').toISOString(),
        },
        {
            userId: 10,
            complaintId: 30,
            action: 'feedback_given',
            details: { rating: 5, comment: 'Streetlight fixed immediately. Perfect!' },
            createdAt: new Date('2024-02-02T14:00:00Z').toISOString(),
        },
    ];

    await db.insert(activityLogs).values(sampleActivityLogs);
    
    console.log('✅ Activity logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});