import { db } from '@/db';
import { complaints } from '@/db/schema';

async function main() {
    const sampleComplaints = [
        // Dadar area (8 complaints)
        {
            userId: 7,
            title: 'Pothole on Dadar TT Circle causing accidents',
            description: 'Large pothole near Dadar TT Circle is causing accidents during monsoon. Multiple two-wheelers have fallen. Needs immediate repair.',
            category: 'infrastructure',
            priority: 'high',
            status: 'in_progress',
            latitude: 19.0187,
            longitude: 72.8478,
            locationAddress: 'Tilak Bridge, Dadar East',
            imageUrl: '/uploads/complaint-1.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
            updatedAt: new Date('2024-01-16T14:20:00').toISOString(),
        },
        {
            userId: 8,
            title: 'Garbage bins overflowing near Dadar Station',
            description: 'Garbage bins near platform 1 entrance are overflowing for past week. Creating hygiene issues and bad smell.',
            category: 'sanitation',
            priority: 'medium',
            status: 'assigned',
            latitude: 19.0190,
            longitude: 72.8430,
            locationAddress: 'Dadar Railway Station, Platform 1',
            imageUrl: '/uploads/complaint-2.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-20T08:15:00').toISOString(),
            updatedAt: new Date('2024-01-21T09:00:00').toISOString(),
        },
        {
            userId: null,
            title: 'Street light not working on Gokhale Road',
            description: 'Street light pole near Ruparel College has not been working for 3 weeks. Dark area causing safety concerns.',
            category: 'streetlight',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0220,
            longitude: 72.8450,
            locationAddress: 'Gokhale Road, Dadar West',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-01T18:30:00').toISOString(),
            updatedAt: new Date('2024-02-01T18:30:00').toISOString(),
        },
        {
            userId: 9,
            title: 'Water pipeline leakage on main road',
            description: 'Major water pipeline leakage on Ranade Road causing water wastage and road damage. Water flowing continuously.',
            category: 'water',
            priority: 'critical',
            status: 'resolved',
            latitude: 19.0170,
            longitude: 72.8500,
            locationAddress: 'Dr. Babasaheb Ambedkar Road, Dadar',
            imageUrl: '/uploads/complaint-3.jpg',
            isAnonymous: false,
            assignedTo: 4,
            resolvedAt: new Date('2024-02-05T16:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-01-28T11:20:00').toISOString(),
            updatedAt: new Date('2024-02-05T16:00:00').toISOString(),
        },
        {
            userId: 10,
            title: 'Broken footpath near Shivaji Park',
            description: 'Footpath tiles broken and uneven near main entrance. Senior citizens finding it difficult to walk.',
            category: 'infrastructure',
            priority: 'medium',
            status: 'assigned',
            latitude: 19.0250,
            longitude: 72.8390,
            locationAddress: 'Shivaji Park Main Road, Dadar',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-03T09:45:00').toISOString(),
            updatedAt: new Date('2024-02-04T10:30:00').toISOString(),
        },
        {
            userId: 11,
            title: 'Illegal dumping near Portuguese Church',
            description: 'Construction waste being dumped illegally near church premises. Need immediate cleanup and action against violators.',
            category: 'sanitation',
            priority: 'high',
            status: 'in_progress',
            latitude: 19.0200,
            longitude: 72.8420,
            locationAddress: 'Portuguese Church Area, Dadar',
            imageUrl: '/uploads/complaint-4.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-08T14:00:00').toISOString(),
            updatedAt: new Date('2024-02-09T11:00:00').toISOString(),
        },
        {
            userId: 12,
            title: 'Bus stop shed damaged in Dadar',
            description: 'Bus stop shed roof collapsed last week. Commuters standing in sun and rain without shelter.',
            category: 'transport',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0160,
            longitude: 72.8460,
            locationAddress: 'Dadar Naka Bus Stop',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-10T16:20:00').toISOString(),
            updatedAt: new Date('2024-02-10T16:20:00').toISOString(),
        },
        {
            userId: 13,
            title: 'Tree branches blocking traffic signal',
            description: 'Overgrown tree branches covering traffic signal near Dadar junction. Causing visibility issues for drivers.',
            category: 'infrastructure',
            priority: 'high',
            status: 'resolved',
            latitude: 19.0195,
            longitude: 72.8485,
            locationAddress: 'Dadar TT Junction',
            imageUrl: '/uploads/complaint-5.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: new Date('2024-02-12T15:30:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-06T12:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T15:30:00').toISOString(),
        },
        
        // Andheri area (7 complaints)
        {
            userId: 14,
            title: 'Major pothole on Western Express Highway',
            description: 'Dangerous pothole on WEH near Andheri Metro causing traffic jams and accidents. Multiple vehicles damaged.',
            category: 'infrastructure',
            priority: 'critical',
            status: 'escalated',
            latitude: 19.1136,
            longitude: 72.8697,
            locationAddress: 'Western Express Highway, Andheri East',
            imageUrl: '/uploads/complaint-6.jpg',
            isAnonymous: false,
            assignedTo: 5,
            resolvedAt: null,
            escalatedAt: new Date('2024-02-13T10:00:00').toISOString(),
            createdAt: new Date('2024-01-25T07:30:00').toISOString(),
            updatedAt: new Date('2024-02-13T10:00:00').toISOString(),
        },
        {
            userId: null,
            title: 'Stray dogs attacking residents in MIDC',
            description: 'Pack of stray dogs attacking residents and workers in MIDC area during evening hours. Need urgent intervention.',
            category: 'health',
            priority: 'high',
            status: 'submitted',
            latitude: 19.1150,
            longitude: 72.8650,
            locationAddress: 'MIDC Road, Andheri East',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-11T19:00:00').toISOString(),
            updatedAt: new Date('2024-02-11T19:00:00').toISOString(),
        },
        {
            userId: 15,
            title: 'Waterlogging near DN Nagar Metro Station',
            description: 'Heavy waterlogging during rain near metro station entrance. Water entering nearby shops and homes.',
            category: 'infrastructure',
            priority: 'high',
            status: 'in_progress',
            latitude: 19.1100,
            longitude: 72.8650,
            locationAddress: 'DN Nagar Metro Station, Andheri West',
            imageUrl: '/uploads/complaint-7.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-30T15:45:00').toISOString(),
            updatedAt: new Date('2024-02-02T11:20:00').toISOString(),
        },
        {
            userId: 16,
            title: 'Street lights not working on SV Road',
            description: 'Multiple street lights not working on SV Road stretch from Andheri to Vile Parle. Dark and unsafe at night.',
            category: 'streetlight',
            priority: 'medium',
            status: 'assigned',
            latitude: 19.1200,
            longitude: 72.8400,
            locationAddress: 'SV Road, Andheri West',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-05T20:00:00').toISOString(),
            updatedAt: new Date('2024-02-06T09:15:00').toISOString(),
        },
        {
            userId: 17,
            title: 'Garbage collection irregular in Lokhandwala',
            description: 'Garbage collection not happening regularly for past 2 weeks. Bins overflowing and creating health hazards.',
            category: 'sanitation',
            priority: 'high',
            status: 'resolved',
            latitude: 19.1400,
            longitude: 72.8350,
            locationAddress: 'Lokhandwala Complex, Andheri West',
            imageUrl: '/uploads/complaint-8.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: new Date('2024-02-14T13:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-01T08:30:00').toISOString(),
            updatedAt: new Date('2024-02-14T13:00:00').toISOString(),
        },
        {
            userId: 18,
            title: 'Bus frequency reduced on Route 444',
            description: 'Bus frequency on Route 444 reduced causing overcrowding. Need more buses during peak hours.',
            category: 'transport',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.1180,
            longitude: 72.8680,
            locationAddress: 'Andheri Bus Depot',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-09T07:00:00').toISOString(),
            updatedAt: new Date('2024-02-09T07:00:00').toISOString(),
        },
        {
            userId: 19,
            title: 'Water supply irregular in Versova',
            description: 'Water supply timing irregular for past month. Residents facing water shortage issues.',
            category: 'water',
            priority: 'medium',
            status: 'assigned',
            latitude: 19.1320,
            longitude: 72.8120,
            locationAddress: 'Versova Village',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 4,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-07T06:30:00').toISOString(),
            updatedAt: new Date('2024-02-08T10:00:00').toISOString(),
        },

        // Bandra area (6 complaints)
        {
            userId: 20,
            title: 'Linking Road footpath encroached by vendors',
            description: 'Street vendors blocking entire footpath on Linking Road. Pedestrians forced to walk on main road.',
            category: 'infrastructure',
            priority: 'low',
            status: 'rejected',
            latitude: 19.0596,
            longitude: 72.8295,
            locationAddress: 'Linking Road, Bandra West',
            imageUrl: '/uploads/complaint-9.jpg',
            isAnonymous: false,
            assignedTo: 5,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-18T16:00:00').toISOString(),
            updatedAt: new Date('2024-01-22T14:30:00').toISOString(),
        },
        {
            userId: 21,
            title: 'Sealink toll plaza causing traffic jams',
            description: 'Only 2 toll booths operational causing massive jams during peak hours. Need more booths open.',
            category: 'transport',
            priority: 'medium',
            status: 'in_progress',
            latitude: 19.0350,
            longitude: 72.8180,
            locationAddress: 'Bandra-Worli Sea Link Toll Plaza',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-04T08:45:00').toISOString(),
            updatedAt: new Date('2024-02-05T09:20:00').toISOString(),
        },
        {
            userId: null,
            title: 'Public toilet near station in poor condition',
            description: 'Public toilet near Bandra station not maintained. Very unhygienic and broken fixtures.',
            category: 'sanitation',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0540,
            longitude: 72.8410,
            locationAddress: 'Bandra Railway Station',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-12T11:30:00').toISOString(),
            updatedAt: new Date('2024-02-12T11:30:00').toISOString(),
        },
        {
            userId: 7,
            title: 'Manhole cover missing on Hill Road',
            description: 'Open manhole without cover on Hill Road near Bandstand. Very dangerous for vehicles and pedestrians.',
            category: 'infrastructure',
            priority: 'critical',
            status: 'resolved',
            latitude: 19.0500,
            longitude: 72.8260,
            locationAddress: 'Hill Road, Bandra West',
            imageUrl: '/uploads/complaint-10.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: new Date('2024-02-11T17:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-08T19:30:00').toISOString(),
            updatedAt: new Date('2024-02-11T17:00:00').toISOString(),
        },
        {
            userId: 8,
            title: 'Street lights flickering in Pali Hill',
            description: 'Multiple street lights flickering and going off intermittently. Electrical issue needs attention.',
            category: 'streetlight',
            priority: 'low',
            status: 'assigned',
            latitude: 19.0550,
            longitude: 72.8240,
            locationAddress: 'Pali Hill, Bandra West',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-10T21:00:00').toISOString(),
            updatedAt: new Date('2024-02-11T10:00:00').toISOString(),
        },
        {
            userId: 9,
            title: 'Carter Road promenade tiles broken',
            description: 'Several tiles on Carter Road promenade are broken and loose. People tripping and getting injured.',
            category: 'infrastructure',
            priority: 'medium',
            status: 'in_progress',
            latitude: 19.0650,
            longitude: 72.8200,
            locationAddress: 'Carter Road, Bandra West',
            imageUrl: '/uploads/complaint-11.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-06T17:15:00').toISOString(),
            updatedAt: new Date('2024-02-07T12:00:00').toISOString(),
        },

        // Kurla area (7 complaints)
        {
            userId: 10,
            title: 'LBS Marg full of potholes near Kurla Station',
            description: 'Entire stretch of LBS Marg near Kurla station has multiple deep potholes. Causing daily accidents.',
            category: 'infrastructure',
            priority: 'critical',
            status: 'in_progress',
            latitude: 19.0728,
            longitude: 72.8826,
            locationAddress: 'LBS Marg, Kurla West',
            imageUrl: '/uploads/complaint-12.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-22T10:00:00').toISOString(),
            updatedAt: new Date('2024-01-24T14:30:00').toISOString(),
        },
        {
            userId: null,
            title: 'Mosquito breeding in stagnant water',
            description: 'Large area of stagnant water near Kurla market causing mosquito breeding. Health hazard for residents.',
            category: 'health',
            priority: 'high',
            status: 'assigned',
            latitude: 19.0700,
            longitude: 72.8800,
            locationAddress: 'Kurla Market Area',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: 3,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-02T08:20:00').toISOString(),
            updatedAt: new Date('2024-02-03T09:30:00').toISOString(),
        },
        {
            userId: 11,
            title: 'Illegal parking blocking main road',
            description: 'Vehicles parked illegally on both sides of road near Kurla terminus causing traffic congestion.',
            category: 'transport',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0760,
            longitude: 72.8850,
            locationAddress: 'LTT Road, Kurla East',
            imageUrl: '/uploads/complaint-13.jpg',
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-13T15:30:00').toISOString(),
            updatedAt: new Date('2024-02-13T15:30:00').toISOString(),
        },
        {
            userId: 12,
            title: 'Drainage choked causing flooding',
            description: 'Main drainage line choked near Phoenix Mall. Even light rain causing flooding in nearby areas.',
            category: 'sanitation',
            priority: 'high',
            status: 'resolved',
            latitude: 19.0880,
            longitude: 72.8930,
            locationAddress: 'LBS Marg, Near Phoenix Mall',
            imageUrl: '/uploads/complaint-14.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: new Date('2024-02-10T16:45:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-01-28T12:00:00').toISOString(),
            updatedAt: new Date('2024-02-10T16:45:00').toISOString(),
        },
        {
            userId: 13,
            title: 'Water pipeline burst in residential area',
            description: 'Major water pipeline burst in Nehru Nagar flooding entire street. Water supply affected.',
            category: 'water',
            priority: 'critical',
            status: 'resolved',
            latitude: 19.0650,
            longitude: 72.8900,
            locationAddress: 'Nehru Nagar, Kurla East',
            imageUrl: '/uploads/complaint-15.jpg',
            isAnonymous: false,
            assignedTo: 4,
            resolvedAt: new Date('2024-02-09T19:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-08T14:30:00').toISOString(),
            updatedAt: new Date('2024-02-09T19:00:00').toISOString(),
        },
        {
            userId: 14,
            title: 'Street light poles rusted and dangerous',
            description: 'Several street light poles near station severely rusted and leaning. Risk of collapse.',
            category: 'streetlight',
            priority: 'high',
            status: 'in_progress',
            latitude: 19.0710,
            longitude: 72.8810,
            locationAddress: 'Station Road, Kurla West',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-11T09:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T10:30:00').toISOString(),
        },
        {
            userId: 15,
            title: 'Illegal construction blocking natural drainage',
            description: 'New construction has blocked natural drainage causing water logging in entire neighborhood.',
            category: 'infrastructure',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0780,
            longitude: 72.8870,
            locationAddress: 'CST Road, Kurla East',
            imageUrl: '/uploads/complaint-16.jpg',
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-14T11:45:00').toISOString(),
            updatedAt: new Date('2024-02-14T11:45:00').toISOString(),
        },

        // Worli area (5 complaints)
        {
            userId: 16,
            title: 'Worli Sea Face promenade needs maintenance',
            description: 'Promenade tiles loose and benches broken. Popular walking spot needs urgent maintenance.',
            category: 'infrastructure',
            priority: 'low',
            status: 'assigned',
            latitude: 19.0176,
            longitude: 72.8187,
            locationAddress: 'Worli Sea Face',
            imageUrl: '/uploads/complaint-17.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-26T16:00:00').toISOString(),
            updatedAt: new Date('2024-01-28T10:00:00').toISOString(),
        },
        {
            userId: null,
            title: 'Traffic signal timing causing congestion',
            description: 'Traffic signal timing at Worli Naka junction incorrect. Causing long queues during peak hours.',
            category: 'transport',
            priority: 'medium',
            status: 'submitted',
            latitude: 19.0130,
            longitude: 72.8200,
            locationAddress: 'Worli Naka Junction',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-08T18:30:00').toISOString(),
            updatedAt: new Date('2024-02-08T18:30:00').toISOString(),
        },
        {
            userId: 17,
            title: 'Garbage dump near BDD Chawl',
            description: 'Unauthorized garbage dump created near BDD Chawl. Unhygienic conditions and bad odor.',
            category: 'sanitation',
            priority: 'high',
            status: 'resolved',
            latitude: 19.0150,
            longitude: 72.8220,
            locationAddress: 'BDD Chawl, Worli',
            imageUrl: '/uploads/complaint-18.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: new Date('2024-02-13T15:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-05T09:00:00').toISOString(),
            updatedAt: new Date('2024-02-13T15:00:00').toISOString(),
        },
        {
            userId: 18,
            title: 'Water supply timing changed without notice',
            description: 'Water supply timing suddenly changed in Worli Village without prior notice. Causing inconvenience.',
            category: 'water',
            priority: 'low',
            status: 'assigned',
            latitude: 19.0200,
            longitude: 72.8150,
            locationAddress: 'Worli Village',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 4,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-10T07:00:00').toISOString(),
            updatedAt: new Date('2024-02-11T09:15:00').toISOString(),
        },
        {
            userId: 19,
            title: 'Street lights not working on Annie Besant Road',
            description: 'Long stretch of Annie Besant Road without working street lights. Very dark and unsafe at night.',
            category: 'streetlight',
            priority: 'medium',
            status: 'in_progress',
            latitude: 19.0190,
            longitude: 72.8170,
            locationAddress: 'Annie Besant Road, Worli',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-07T20:00:00').toISOString(),
            updatedAt: new Date('2024-02-08T10:30:00').toISOString(),
        },

        // Other scattered locations (17 complaints)
        {
            userId: 20,
            title: 'Mumbai Central station footbridge needs repair',
            description: 'Footbridge at Mumbai Central station has damaged steps. Safety hazard for commuters.',
            category: 'transport',
            priority: 'medium',
            status: 'submitted',
            latitude: 18.9685,
            longitude: 72.8195,
            locationAddress: 'Mumbai Central Railway Station',
            imageUrl: '/uploads/complaint-19.jpg',
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-01T12:00:00').toISOString(),
            updatedAt: new Date('2024-02-01T12:00:00').toISOString(),
        },
        {
            userId: 21,
            title: 'Matunga station platform overcrowding',
            description: 'Platform 1 at Matunga station extremely overcrowded during peak hours. Need better crowd management.',
            category: 'transport',
            priority: 'low',
            status: 'rejected',
            latitude: 19.0257,
            longitude: 72.8466,
            locationAddress: 'Matunga Railway Station',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 5,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-19T08:30:00').toISOString(),
            updatedAt: new Date('2024-01-25T14:00:00').toISOString(),
        },
        {
            userId: null,
            title: 'Broken glass on Haji Ali footpath',
            description: 'Broken glass bottles scattered on footpath near Haji Ali Dargah. Dangerous for barefoot devotees.',
            category: 'sanitation',
            priority: 'medium',
            status: 'resolved',
            latitude: 18.9826,
            longitude: 72.8089,
            locationAddress: 'Haji Ali Dargah Road',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: 3,
            resolvedAt: new Date('2024-02-06T16:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-04T14:30:00').toISOString(),
            updatedAt: new Date('2024-02-06T16:00:00').toISOString(),
        },
        {
            userId: 7,
            title: 'Wadala truck terminal causing air pollution',
            description: 'Heavy trucks at Wadala terminal running engines idle for hours. Severe air pollution in residential area.',
            category: 'health',
            priority: 'medium',
            status: 'assigned',
            latitude: 19.0176,
            longitude: 72.8561,
            locationAddress: 'Wadala Truck Terminal',
            imageUrl: '/uploads/complaint-20.jpg',
            isAnonymous: false,
            assignedTo: 5,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-09T10:00:00').toISOString(),
            updatedAt: new Date('2024-02-10T11:30:00').toISOString(),
        },
        {
            userId: 8,
            title: 'BMC school building in dilapidated condition',
            description: 'Municipal school building in Parel showing cracks. Safety concern for students and teachers.',
            category: 'education',
            priority: 'critical',
            status: 'in_progress',
            latitude: 19.0033,
            longitude: 72.8417,
            locationAddress: 'BMC School, Parel',
            imageUrl: '/uploads/complaint-21.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-01-23T09:15:00').toISOString(),
            updatedAt: new Date('2024-01-25T10:30:00').toISOString(),
        },
        {
            userId: 9,
            title: 'Sewage overflow in Lower Parel',
            description: 'Sewage overflowing from manholes in Lower Parel area. Unhygienic conditions and bad smell.',
            category: 'sanitation',
            priority: 'critical',
            status: 'resolved',
            latitude: 18.9969,
            longitude: 72.8302,
            locationAddress: 'Lower Parel',
            imageUrl: '/uploads/complaint-22.jpg',
            isAnonymous: false,
            assignedTo: 3,
            resolvedAt: new Date('2024-02-12T18:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-07T11:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T18:00:00').toISOString(),
        },
        {
            userId: 10,
            title: 'Dangerous crossing at Sion Circle',
            description: 'No proper zebra crossing at Sion Circle. Pedestrians risking lives to cross busy junction.',
            category: 'infrastructure',
            priority: 'high',
            status: 'submitted',
            latitude: 19.0433,
            longitude: 72.8636,
            locationAddress: 'Sion Circle',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-13T17:00:00').toISOString(),
            updatedAt: new Date('2024-02-13T17:00:00').toISOString(),
        },
        {
            userId: 11,
            title: 'Mahalaxmi Racecourse road needs resurfacing',
            description: 'Road near Mahalaxmi Racecourse completely damaged with multiple potholes. Needs complete resurfacing.',
            category: 'infrastructure',
            priority: 'medium',
            status: 'assigned',
            latitude: 18.9827,
            longitude: 72.8240,
            locationAddress: 'Mahalaxmi Racecourse',
            imageUrl: '/uploads/complaint-23.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-03T13:30:00').toISOString(),
            updatedAt: new Date('2024-02-04T09:00:00').toISOString(),
        },
        {
            userId: null,
            title: 'Churchgate station toilet in poor condition',
            description: 'Ladies toilet at Churchgate station not maintained properly. Very unhygienic.',
            category: 'sanitation',
            priority: 'low',
            status: 'submitted',
            latitude: 18.9354,
            longitude: 72.8269,
            locationAddress: 'Churchgate Railway Station',
            imageUrl: null,
            isAnonymous: true,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-11T15:00:00').toISOString(),
            updatedAt: new Date('2024-02-11T15:00:00').toISOString(),
        },
        {
            userId: 12,
            title: 'Broken swings in Shivaji Park playground',
            description: 'Multiple swings and slides broken in children playground. Kids getting injured.',
            category: 'other',
            priority: 'low',
            status: 'assigned',
            latitude: 19.0289,
            longitude: 72.8397,
            locationAddress: 'Shivaji Park Playground',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-05T16:30:00').toISOString(),
            updatedAt: new Date('2024-02-06T10:00:00').toISOString(),
        },
        {
            userId: 13,
            title: 'Water pressure very low in Mahim',
            description: 'Water pressure extremely low on upper floors. Tanks not filling properly.',
            category: 'water',
            priority: 'medium',
            status: 'in_progress',
            latitude: 19.0395,
            longitude: 72.8403,
            locationAddress: 'Mahim West',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 4,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-08T06:00:00').toISOString(),
            updatedAt: new Date('2024-02-09T09:30:00').toISOString(),
        },
        {
            userId: 14,
            title: 'Grant Road bridge needs immediate repair',
            description: 'Road bridge showing structural cracks. Heavy traffic passing daily. Urgent inspection needed.',
            category: 'infrastructure',
            priority: 'critical',
            status: 'resolved',
            latitude: 18.9655,
            longitude: 72.8151,
            locationAddress: 'Grant Road Bridge',
            imageUrl: '/uploads/complaint-24.jpg',
            isAnonymous: false,
            assignedTo: 2,
            resolvedAt: new Date('2024-02-14T17:30:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-01-29T11:00:00').toISOString(),
            updatedAt: new Date('2024-02-14T17:30:00').toISOString(),
        },
        {
            userId: 15,
            title: 'Street light pole electrocuting people',
            description: 'Faulty street light pole near Tardeo giving electric shocks. Two people injured already.',
            category: 'streetlight',
            priority: 'critical',
            status: 'resolved',
            latitude: 18.9698,
            longitude: 72.8150,
            locationAddress: 'Tardeo Road',
            imageUrl: '/uploads/complaint-25.jpg',
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: new Date('2024-02-11T14:00:00').toISOString(),
            escalatedAt: null,
            createdAt: new Date('2024-02-10T18:30:00').toISOString(),
            updatedAt: new Date('2024-02-11T14:00:00').toISOString(),
        },
        {
            userId: 16,
            title: 'Breach Candy swimming pool needs renovation',
            description: 'Public swimming pool at Breach Candy in poor condition. Water not properly treated.',
            category: 'health',
            priority: 'low',
            status: 'submitted',
            latitude: 18.9738,
            longitude: 72.8048,
            locationAddress: 'Breach Candy',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-12T14:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T14:00:00').toISOString(),
        },
        {
            userId: 17,
            title: 'Lack of benches at Marine Drive',
            description: 'Many benches at Marine Drive broken or removed. Senior citizens have nowhere to sit.',
            category: 'infrastructure',
            priority: 'low',
            status: 'submitted',
            latitude: 18.9432,
            longitude: 72.8234,
            locationAddress: 'Marine Drive',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: null,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-14T16:00:00').toISOString(),
            updatedAt: new Date('2024-02-14T16:00:00').toISOString(),
        },
        {
            userId: 18,
            title: 'School zone speed limits not enforced',
            description: 'Vehicles speeding in school zone near KC College. Need speed breakers and enforcement.',
            category: 'education',
            priority: 'medium',
            status: 'assigned',
            latitude: 18.9301,
            longitude: 72.8278,
            locationAddress: 'Churchgate, Near KC College',
            imageUrl: null,
            isAnonymous: false,
            assignedTo: 5,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-06T08:00:00').toISOString(),
            updatedAt: new Date('2024-02-07T09:30:00').toISOString(),
        },
        {
            userId: 19,
            title: 'Bus stop shelter collapsed in Chembur',
            description: 'Bus stop shelter near Diamond Garden collapsed last night. Commuters without protection from rain.',
            category: 'transport',
            priority: 'high',
            status: 'in_progress',
            latitude: 19.0634,
            longitude: 72.9020,
            locationAddress: 'Diamond Garden, Chembur',
            imageUrl: '/uploads/complaint-26.jpg',
            isAnonymous: false,
            assignedTo: 6,
            resolvedAt: null,
            escalatedAt: null,
            createdAt: new Date('2024-02-13T07:00:00').toISOString(),
            updatedAt: new Date('2024-02-13T13:00:00').toISOString(),
        },
    ];

    await db.insert(complaints).values(sampleComplaints);
    
    console.log('✅ Complaints seeder completed successfully - 50 complaints created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});