import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        // complaint_status notifications (15 total)
        {
            userId: 7,
            complaintId: 1,
            title: 'Complaint Status Updated',
            message: 'Your complaint #1 status changed to assigned',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-01-15T09:30:00').toISOString(),
        },
        {
            userId: 8,
            complaintId: 3,
            title: 'Complaint Status Updated',
            message: 'Your complaint #3 status changed to in_progress',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-01-18T14:20:00').toISOString(),
        },
        {
            userId: 9,
            complaintId: 5,
            title: 'Complaint Status Updated',
            message: 'Complaint #5 has been resolved',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-01-22T10:45:00').toISOString(),
        },
        {
            userId: 10,
            complaintId: 7,
            title: 'Complaint Status Updated',
            message: 'Your complaint #7 status changed to escalated',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-01-25T16:10:00').toISOString(),
        },
        {
            userId: 11,
            complaintId: 9,
            title: 'Complaint Status Updated',
            message: 'Your complaint #9 status changed to resolved',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-02-01T08:15:00').toISOString(),
        },
        {
            userId: 7,
            complaintId: 11,
            title: 'Complaint Status Updated',
            message: 'Complaint #11 has been resolved successfully',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-02-05T11:30:00').toISOString(),
        },
        {
            userId: 8,
            complaintId: 13,
            title: 'Complaint Status Updated',
            message: 'Your complaint #13 status changed to in_progress',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-02-08T13:45:00').toISOString(),
        },
        {
            userId: 12,
            complaintId: 15,
            title: 'Complaint Status Updated',
            message: 'Your complaint #15 has been assigned to the infrastructure department',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-02-12T09:20:00').toISOString(),
        },
        {
            userId: 13,
            complaintId: 17,
            title: 'Complaint Status Updated',
            message: 'Complaint #17 has been resolved',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-02-15T15:10:00').toISOString(),
        },
        {
            userId: 14,
            complaintId: 19,
            title: 'Complaint Status Updated',
            message: 'Your complaint #19 status changed to rejected',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-02-18T10:30:00').toISOString(),
        },
        {
            userId: 15,
            complaintId: 21,
            title: 'Complaint Status Updated',
            message: 'Your complaint #21 status changed to assigned',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-02-22T14:15:00').toISOString(),
        },
        {
            userId: 9,
            complaintId: 23,
            title: 'Complaint Status Updated',
            message: 'Complaint #23 has been resolved',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-02-25T11:40:00').toISOString(),
        },
        {
            userId: 10,
            complaintId: 25,
            title: 'Complaint Status Updated',
            message: 'Your complaint #25 status changed to in_progress',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-02-28T09:55:00').toISOString(),
        },
        {
            userId: 11,
            complaintId: 27,
            title: 'Complaint Status Updated',
            message: 'Your complaint #27 has been resolved successfully',
            type: 'complaint_status',
            isRead: false,
            createdAt: new Date('2024-03-02T16:20:00').toISOString(),
        },
        {
            userId: 12,
            complaintId: 29,
            title: 'Complaint Status Updated',
            message: 'Complaint #29 status changed to escalated',
            type: 'complaint_status',
            isRead: true,
            createdAt: new Date('2024-03-05T13:30:00').toISOString(),
        },

        // assignment notifications (12 total)
        {
            userId: 2,
            complaintId: 1,
            title: 'New Complaint Assigned',
            message: 'Complaint #1 has been assigned to you: Pothole on Main Street needs urgent repair',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-01-15T09:00:00').toISOString(),
        },
        {
            userId: 3,
            complaintId: 2,
            title: 'New Complaint Assigned',
            message: 'Complaint #2 has been assigned to you: Overflowing garbage bins in residential area',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-01-16T10:30:00').toISOString(),
        },
        {
            userId: 4,
            complaintId: 4,
            title: 'New Complaint Assigned',
            message: 'Complaint #4 has been assigned to you: Traffic signal malfunction at downtown intersection',
            type: 'assignment',
            isRead: false,
            createdAt: new Date('2024-01-20T08:45:00').toISOString(),
        },
        {
            userId: 5,
            complaintId: 6,
            title: 'New Complaint Assigned',
            message: 'Complaint #6 has been assigned to you: Multiple streetlights not working in neighborhood',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-01-24T11:15:00').toISOString(),
        },
        {
            userId: 6,
            complaintId: 8,
            title: 'New Complaint Assigned',
            message: 'Complaint #8 has been assigned to you: Water leakage from main pipeline',
            type: 'assignment',
            isRead: false,
            createdAt: new Date('2024-01-28T14:20:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: 10,
            title: 'New Complaint Assigned',
            message: 'Complaint #10 has been assigned to you: Damaged road signs on highway exit',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-02-03T09:30:00').toISOString(),
        },
        {
            userId: 3,
            complaintId: 12,
            title: 'New Complaint Assigned',
            message: 'Complaint #12 has been assigned to you: Illegal dumping in public park area',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-02-07T15:40:00').toISOString(),
        },
        {
            userId: 4,
            complaintId: 14,
            title: 'New Complaint Assigned',
            message: 'Complaint #14 has been assigned to you: Bus stop shelter damaged and needs repair',
            type: 'assignment',
            isRead: false,
            createdAt: new Date('2024-02-11T10:20:00').toISOString(),
        },
        {
            userId: 5,
            complaintId: 16,
            title: 'New Complaint Assigned',
            message: 'Complaint #16 has been assigned to you: Street light pole leaning dangerously',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-02-14T13:50:00').toISOString(),
        },
        {
            userId: 6,
            complaintId: 18,
            title: 'New Complaint Assigned',
            message: 'Complaint #18 has been assigned to you: Low water pressure in residential complex',
            type: 'assignment',
            isRead: false,
            createdAt: new Date('2024-02-19T11:10:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: 22,
            title: 'New Complaint Assigned',
            message: 'Complaint #22 has been assigned to you: Broken footpath causing safety hazard',
            type: 'assignment',
            isRead: true,
            createdAt: new Date('2024-02-24T08:30:00').toISOString(),
        },
        {
            userId: 3,
            complaintId: 26,
            title: 'New Complaint Assigned',
            message: 'Complaint #26 has been assigned to you: Stray dog menace in residential area',
            type: 'assignment',
            isRead: false,
            createdAt: new Date('2024-03-01T14:45:00').toISOString(),
        },

        // escalation notifications (3 total)
        {
            userId: 1,
            complaintId: 7,
            title: 'Complaint Escalated',
            message: 'Complaint #7 has been escalated for priority attention due to prolonged inaction',
            type: 'escalation',
            isRead: true,
            createdAt: new Date('2024-01-25T16:00:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: 20,
            title: 'Complaint Escalated',
            message: 'Complaint #20 has been escalated for priority attention - requires immediate action',
            type: 'escalation',
            isRead: false,
            createdAt: new Date('2024-02-20T10:15:00').toISOString(),
        },
        {
            userId: 1,
            complaintId: 29,
            title: 'Complaint Escalated',
            message: 'Complaint #29 has been escalated for priority attention - critical infrastructure issue',
            type: 'escalation',
            isRead: true,
            createdAt: new Date('2024-03-05T13:20:00').toISOString(),
        },

        // feedback notifications (7 total)
        {
            userId: 2,
            complaintId: 5,
            title: 'Feedback Received',
            message: 'You received 5 stars feedback on complaint #5',
            type: 'feedback',
            isRead: true,
            createdAt: new Date('2024-01-23T12:30:00').toISOString(),
        },
        {
            userId: 3,
            complaintId: 9,
            title: 'Feedback Received',
            message: 'You received 4 stars feedback on complaint #9',
            type: 'feedback',
            isRead: true,
            createdAt: new Date('2024-02-02T15:20:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: 11,
            title: 'Feedback Received',
            message: 'You received 5 stars feedback on complaint #11',
            type: 'feedback',
            isRead: false,
            createdAt: new Date('2024-02-06T09:45:00').toISOString(),
        },
        {
            userId: 4,
            complaintId: 17,
            title: 'Feedback Received',
            message: 'You received 3 stars feedback on complaint #17',
            type: 'feedback',
            isRead: true,
            createdAt: new Date('2024-02-16T11:30:00').toISOString(),
        },
        {
            userId: 5,
            complaintId: 23,
            title: 'Feedback Received',
            message: 'You received 5 stars feedback on complaint #23',
            type: 'feedback',
            isRead: false,
            createdAt: new Date('2024-02-26T14:10:00').toISOString(),
        },
        {
            userId: 6,
            complaintId: 27,
            title: 'Feedback Received',
            message: 'You received 4 stars feedback on complaint #27',
            type: 'feedback',
            isRead: true,
            createdAt: new Date('2024-03-03T10:25:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: 30,
            title: 'Feedback Received',
            message: 'You received 5 stars feedback on complaint #30',
            type: 'feedback',
            isRead: false,
            createdAt: new Date('2024-03-06T16:40:00').toISOString(),
        },

        // system notifications (3 total)
        {
            userId: 1,
            complaintId: null,
            title: 'System Maintenance',
            message: 'Scheduled system maintenance will be performed on March 15th from 2:00 AM to 4:00 AM. Services may be temporarily unavailable.',
            type: 'system',
            isRead: true,
            createdAt: new Date('2024-03-08T10:00:00').toISOString(),
        },
        {
            userId: 2,
            complaintId: null,
            title: 'New Feature Available',
            message: 'We have introduced bulk complaint assignment feature for authorities. Check it out in your dashboard!',
            type: 'system',
            isRead: false,
            createdAt: new Date('2024-03-09T09:30:00').toISOString(),
        },
        {
            userId: 7,
            complaintId: null,
            title: 'Policy Update',
            message: 'Our complaint handling policy has been updated. Anonymous complaints will now require additional verification before assignment.',
            type: 'system',
            isRead: true,
            createdAt: new Date('2024-03-10T14:15:00').toISOString(),
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});