import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const saltRounds = 10;

    // Hash all passwords
    const adminPassword = await bcrypt.hash('Admin123!', saltRounds);
    const infraPassword = await bcrypt.hash('Infra123!', saltRounds);
    const sanitPassword = await bcrypt.hash('Sanit123!', saltRounds);
    const transPassword = await bcrypt.hash('Trans123!', saltRounds);
    const lightPassword = await bcrypt.hash('Light123!', saltRounds);
    const waterPassword = await bcrypt.hash('Water123!', saltRounds);
    const citizenPassword = await bcrypt.hash('Citizen123!', saltRounds);

    const sampleUsers = [
        // 1 Admin User
        {
            email: 'admin@civiq.com',
            passwordHash: adminPassword,
            fullName: 'CIViQ Admin',
            phone: '+91 9876543210',
            role: 'admin',
            trustScore: 100.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        
        // 5 Authority Users
        {
            email: 'infra@civiq.com',
            passwordHash: infraPassword,
            fullName: 'Infrastructure Manager',
            phone: '+91 9876543211',
            role: 'authority',
            trustScore: 92.5,
            department: 'infrastructure',
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            email: 'sanitation@civiq.com',
            passwordHash: sanitPassword,
            fullName: 'Sanitation Officer',
            phone: '+91 9876543212',
            role: 'authority',
            trustScore: 88.0,
            department: 'sanitation',
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            email: 'transport@civiq.com',
            passwordHash: transPassword,
            fullName: 'Transport Controller',
            phone: '+91 9876543213',
            role: 'authority',
            trustScore: 90.5,
            department: 'transport',
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            email: 'streetlight@civiq.com',
            passwordHash: lightPassword,
            fullName: 'Streetlight Manager',
            phone: '+91 9876543214',
            role: 'authority',
            trustScore: 87.5,
            department: 'streetlight',
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            email: 'water@civiq.com',
            passwordHash: waterPassword,
            fullName: 'Water Department Head',
            phone: '+91 9876543215',
            role: 'authority',
            trustScore: 93.0,
            department: 'water',
            isActive: true,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },

        // 15 Citizen Users
        {
            email: 'rajesh.kumar@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Rajesh Kumar',
            phone: '+91 9845678901',
            role: 'citizen',
            trustScore: 95.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            email: 'priya.sharma@yahoo.com',
            passwordHash: citizenPassword,
            fullName: 'Priya Sharma',
            phone: '+91 9845678902',
            role: 'citizen',
            trustScore: 88.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            email: 'amit.patel@outlook.com',
            passwordHash: citizenPassword,
            fullName: 'Amit Patel',
            phone: '+91 9845678903',
            role: 'citizen',
            trustScore: 92.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            email: 'sneha.reddy@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Sneha Reddy',
            phone: '+91 9845678904',
            role: 'citizen',
            trustScore: 100.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            email: 'vikram.singh@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Vikram Singh',
            phone: '+91 9845678905',
            role: 'citizen',
            trustScore: 78.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            email: 'anita.mehta@yahoo.com',
            passwordHash: citizenPassword,
            fullName: 'Anita Mehta',
            phone: '+91 9845678906',
            role: 'citizen',
            trustScore: 85.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            email: 'rahul.verma@outlook.com',
            passwordHash: citizenPassword,
            fullName: 'Rahul Verma',
            phone: '+91 9845678907',
            role: 'citizen',
            trustScore: 90.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            email: 'deepa.nair@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Deepa Nair',
            phone: '+91 9845678908',
            role: 'citizen',
            trustScore: 94.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            email: 'arun.joshi@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Arun Joshi',
            phone: '+91 9845678909',
            role: 'citizen',
            trustScore: 82.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            email: 'kavita.gupta@yahoo.com',
            passwordHash: citizenPassword,
            fullName: 'Kavita Gupta',
            phone: '+91 9845678910',
            role: 'citizen',
            trustScore: 97.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            email: 'suresh.iyer@outlook.com',
            passwordHash: citizenPassword,
            fullName: 'Suresh Iyer',
            phone: '+91 9845678911',
            role: 'citizen',
            trustScore: 75.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            email: 'meera.krishnan@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Meera Krishnan',
            phone: '+91 9845678912',
            role: 'citizen',
            trustScore: 89.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            email: 'naveen.rao@gmail.com',
            passwordHash: citizenPassword,
            fullName: 'Naveen Rao',
            phone: '+91 9845678913',
            role: 'citizen',
            trustScore: 86.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            email: 'pooja.desai@yahoo.com',
            passwordHash: citizenPassword,
            fullName: 'Pooja Desai',
            phone: '+91 9845678914',
            role: 'citizen',
            trustScore: 91.5,
            department: null,
            isActive: true,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            email: 'karthik.menon@outlook.com',
            passwordHash: citizenPassword,
            fullName: 'Karthik Menon',
            phone: '+91 9845678915',
            role: 'citizen',
            trustScore: 70.0,
            department: null,
            isActive: true,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
    ];

    await db.insert(users).values(sampleUsers);

    console.log('✅ Users seeder completed successfully - 21 users created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});